from snakemake.utils import min_version


min_version("6.10.0")


configfile: "config/config.yaml"


# declare https://github.com/nikostr/read-mapping as a module
module read_mapping:
    snakefile: 
        github("nikostr/read-mapping", path="workflow/Snakefile", tag="v0.2")
    config:
        config


# use all rules from https://github.com/nikostr/read-mapping
use rule * from read_mapping as read_mapping_*

include: "rules/common.smk"
include: "rules/calling.smk"

rule all:
    input:
        "results/calls/calls.vcf",
    default_target: True
