from snakemake.utils import min_version


min_version("6.10.0")


configfile: "config/config.yaml"


# declare https://github.com/nikostr/read-mapping as a module
module read_mapping:
    snakefile:
        github("nikostr/read-mapping", path="workflow/Snakefile", tag="v0.3.0")
    config:
        config


# use all rules from https://github.com/nikostr/read-mapping
use rule * from read_mapping as read_mapping_*


include: "rules/common.smk"
include: "rules/calling.smk"
include: "rules/qc.smk"
include: "rules/mappability-map.smk"
include: "rules/delly_calling.smk"
include: "rules/cnv_calling.smk"


rule all:
    input:
        rules.compress_vcf.output,
        "results/qc/multiqc.html",
    default_target: True
